### ISSUE TITLE
Strategies for modifying generated api clients.

### ISSUE THREAD

**Issue by ehennestad** [mathworks-ref-arch/matlab-openapi-generator#3]
There are some cases where I need to modify the generated classes, i.e by modifying the preSend method to add the bearerToken to all headers, or to customize code due to inconsistencies in the schema specs.

Are there any strategies I should keep in mind if I need to regenerate the api classes, i.e if the API specs have been updated?

**Comment by brownemi** [comment]
A `presend` modification for authentication is a common requirement and is perhaps the main reason present exists. My advice would be:

*  Use source control of some form so if you regenerate you don't lose your changes all in one go and can check what changed.
*  From presend etc. call a function perhaps in separate namespace rather than several lines of code, https://www.mathworks.com/help/matlab/matlab_oop/scoping-classes-with-packages.html so that your code is more distinct from the generated code and reinserting just one line of code adds your functionality back and diffs/merges are simpler.
* Try to use the BaseClient for common functionality so that changes propagate to all derived API classes.
* The generator takes standard openapi-tools arguments that would allow you to only regenerate the APIs or the Models or subsets but this would require that you know specifically what has changed in the spec so that things stay consistent. This is mostly useful if you're editing the spec itself.
* You can also use a .openapi-generator-ignore file to define files to not regenerate.
* Source control the spec too, especially if you need to alter it.
* We do hope to make some improvements to this package over time too. So in addition to spec changes the generator can change too. With that in mind it note that we record what version of the package was used in a comment in the file headers. Just something to be aware of if comparing versions created at different times.

**Comment by ehennestad** [comment]
This is very helpful, thanks!

**Comment by brownemi** [comment]
https://github.com/mathworks-ref-arch/matlab-openapi-generator/blob/main/Documentation/CustomizingGeneratedCode.md has been updated based on this issue and will be published in the next release (>v1.0.9).
